---
title: "background_points"
format: html
editor: visual
---

## Code for creating background points

```{r}
library(raster)
library(sdmpredictors)
#Get data from the sdmpredictors package
layercodes <- c("BO_nitrate")
env <- sdmpredictors::load_layers(layercodes, equalarea = FALSE)

#Crop
e <- raster::extent(-71, -64, 42, 45)
rc <- raster::crop(env, e)

#Plot	
raster::plot(rc)
```

```{r}
#Setting seed for reproducibility
set.seed(42)

#Setting number of background points required
nsamp <- 1000

#Create background points
background <- randomPoints(rc, nsamp) %>% 
  #Transform to tibble
  as_tibble() %>% 
  #Transform to sf object
  st_as_sf(coords = c("x", "y"), crs = 4326)

mapview(background, col.regions = "gray")

# Convert the sf object to a data frame
background_df <- as.data.frame(background)

# Save the background points to a CSV file
write.csv(background_df, file = "background_points.csv", row.names = FALSE)
getwd()
```

The `echo: false` option disables the printing of code (only output is displayed).
