species:
- Doryteuthis pealeii
- Cetorhinus maximus
latmin: 42.0
latmax: 45.0
lonmin: -71.0
lonmax: -64.0
envVars:
- pH
- Surface Temperature
- Bottom Temperature
- Dissolved Oxygen
- Surface salinity
- Bottom salinity
- Chlorophyll
- Depth
