---
title: "Obis"
format: html
editor: visual
---

#Important notes!
Dataset list is available HERE https://erddap.bio-oracle.org/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=Bio-OracleS

### Step 1: Import Libraries
```{r}
#For getting species data -- not used here:
library(robis)
#For data manipultaion: 
library(tidyverse)
#Not used, but anohter method to get data:
#library(rerddap)
#Get genera API data:
#library(httr)
library(lubridate)
library(sdmpredictors)
```



## To see datasets
```{r}
datasets <- list_datasets(terrestrial = FALSE, marine = TRUE)
#View(datasets[,c("dataset_code", "description")])
layers <- list_layers(datasets)
layers
```

## Future datasets
```{r}
future <- list_layers_future(terrestrial = FALSE) 
# available scenarios 
future
```



```{r}
dir <- "ohw-tutorials/data"
# download pH and Salinity to the temporary directory
load_layers(layers[layers$name %in% c("pH") & 
                     layers$dataset_code == "Bio-ORACLE",], datadir = dir)

# set a default datadir, preferably something different from tempdir()
options(sdmpredictors_datadir= dir)

# (down)load specific layers 
specific <- load_layers(c("BO_ph"))

# equal area data (Behrmann equal area projection) 
equalarea <- load_layers("BO_ph", equalarea = TRUE)
plot(equalarea)
```
```{r}
layercodes <- c("BO_nitrate")
env <- load_layers(layercodes, equalarea = FALSE)

```

## Or even simpler: 
```{r}
oct <- load_layers("MS_sst10_5m")

```

# Next steps
- Crop rasters




